/* N.B. This was the old software to read from the last attempt using
   `CPK' rather than `QTree'.
*/



/***************************************************************************

   Program:    ViewCPK
   File:       ReadImage.c
   
   Version:    V1.0
   Date:       18.03.92
   Function:   Reads a CPK image generated by VaxCPK.
   
   Copyright:  SciTech Software 1992
   Author:     Dr. Andrew C. R. Martin
   Address:    SciTech Software
               23, Stag Leys,
               Ashtead,
               Surrey,
               KT21 2TD.
   Phone:      +44 (0372) 275775
   EMail:      UUCP: cbmuk!cbmuka!scitec!amartin
               JANET: andrew@uk.ac.ox.biop
               
****************************************************************************

   This program is not in the public domain, but it may be freely copied
   and distributed for no charge providing this header is included.
   The code may be modified as required, but any modifications must be
   documented so that the person responsible can be identified. If someone
   else breaks this code, I don't want to be blamed for code that does not
   work! The code may not be sold commercially without prior permission from
   the author, although it may be given away free with commercial products,
   providing it is made clear that this program is free and that the source
   code is provided with the program.

****************************************************************************

   Description:
   ============
   This C routine reads a C binary image file written by VaxCPK.

****************************************************************************

   Usage:
   ======
   Must be linked with ViewCPK.for
   Communication between C and FORTRAN is via a common block.

****************************************************************************

   Revision History:
   =================

/**************************************************************************/
/* Standard includes
*/
#include <stdio.h>

***************************************************************************/
/* Definitions
*/
#define NX  1024
#define NY  1024

/**************************************************************************/
/* External definition to link with the FORTRAN common block
*/
extern struct
{
   unsigned char fbuf[1024][1024];
}  imgcmn;

/**************************************************************************/
readimage(int *nreject)
{
   int   x,y;
   FILE  *fp;
   char  filename[160];
   
   printf("Name of image file to display: ");
   sscanf("%s",filename);
   
   if((fp=fopen(filename,"rb"))==NULL)
   {
      printf("Unable to open image file %s\n",filename);
      exit(0);
   }
   
   for(y=0; y < NY-(*nreject); y++)
   {
      fread(&(imgcmn.fbuf[y][0]),sizeof(unsigned char),NX,fp);
   }
   
   return(0);
}
