#!/bin/sh
# Short script to copy the required files from bioplib for creation
# of a distribution version of QTree
# V1.0  21.12.94 By: ACRM
# V1.1  18.06.96 Added bioplib/ZonePDB.c

BIOP=/home/bsm/martin/include/bioplib
QTREE=QTreeV2.1
QTBIOP=$QTREE/bioplib
QTEXTRAS=$QTREE/extras

# Create subdirectories
if [ -d $QTREE ]
then
   echo "Got QTree directory"
else
   echo "Creating QTree directory"
   mkdir $QTREE
fi

if [ -d $QTBIOP ] 
then
   echo "Got bioplib sub-directory"
else
   echo "Creating bioplib sub-directory"
   mkdir $QTBIOP
fi

if [ -d $QTEXTRAS ] 
then
   echo "Got extras sub-directory"
else
   echo "Creating extras sub-directory"
   mkdir $QTEXTRAS
fi

# Copy bioplib files into directory
cp ${BIOP}/macros.h     $QTBIOP
cp ${BIOP}/MathType.h   $QTBIOP
cp ${BIOP}/SysDefs.h    $QTBIOP
cp ${BIOP}/pdb.h        $QTBIOP
cp ${BIOP}/help.h       $QTBIOP
cp ${BIOP}/parse.h      $QTBIOP
cp ${BIOP}/general.h    $QTBIOP
cp ${BIOP}/matrix.h     $QTBIOP
cp ${BIOP}/WindIO.h     $QTBIOP
cp ${BIOP}/fsscanf.h    $QTBIOP
cp ${BIOP}/CursWind.h   $QTBIOP
cp ${BIOP}/angle.h      $QTBIOP
cp ${BIOP}/array.h      $QTBIOP
cp ${BIOP}/RotPDB.c     $QTBIOP
cp ${BIOP}/ReadPDB.c    $QTBIOP
cp ${BIOP}/WritePDB.c   $QTBIOP
cp ${BIOP}/help.c       $QTBIOP
cp ${BIOP}/matrix.c     $QTBIOP
cp ${BIOP}/parse.c      $QTBIOP
cp ${BIOP}/angle.c      $QTBIOP
cp ${BIOP}/general.c    $QTBIOP
cp ${BIOP}/fsscanf.c    $QTBIOP
cp ${BIOP}/WindIO.c     $QTBIOP
cp ${BIOP}/ModPDB.c     $QTBIOP
cp ${BIOP}/ApMatPDB.c   $QTBIOP
cp ${BIOP}/OrigPDB.c    $QTBIOP
cp ${BIOP}/GetCGPDB.c   $QTBIOP
cp ${BIOP}/ParseRes.c   $QTBIOP
cp ${BIOP}/CalcPDB.c    $QTBIOP
cp ${BIOP}/PDBList.c    $QTBIOP
cp ${BIOP}/array.c      $QTBIOP
cp ${BIOP}/ZonePDB.c    $QTBIOP
cp ${BIOP}/COPYING.DOC  $QTBIOP

# Copy in the extras files
cp extras/ColourGraphics.c $QTEXTRAS
cp extras/GreyGraphics.c   $QTEXTRAS
cp extras/mtvham.c         $QTEXTRAS
cp extras/ReadMTV.c        $QTEXTRAS

# Copy source code into directory
cp *.c *.h *.p          $QTREE

# Copy documentation into directory
cp *.hlp                $QTREE
cp 00Read.Me            $QTREE
cp COPYING.DOC          $QTREE

# Copy distribution specials into directory
cp ./distspecial/makefile       $QTREE
cp ./distspecial/restype.dat    $QTREE
cp ./distspecial/00READ.ME      $QTBIOP

# Tar up the distribution directory
tar -cvf ${QTREE}.tar $QTREE
gzip ${QTREE}.tar

# and finally delete the directory
/bin/rm -rf $QTREE


